name: Deploy

on:
  push:

env:
  REGISTRY_NAME: dsmsacr
  NAMESPACE: demo-e2e
  APP_NAME: security-policy-app-staging
  PROD_APP_NAME: security-policy-app-prod
  RESOURCE_GROUP: az-pac-demo

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    
    - name: Building the Docker image
      run: |
        docker build . --tag demo-e2e
    
    - uses: ds-ms/container-scan@releases/v0
      name: Container Scan
      id: imagescan
      with:
        image-name: demo-e2e

    - name: Upload Container Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.imagescan.outputs.sarif-file-path }}
